language: go
sudo: false

go:
  - "1.10"
  - "1.11"
  - tip

install:
  - go get github.com/mattn/goveralls
  - go get -d -v ./...
script:
  - go test -v -covermode=count -coverprofile=profile.cov
after_success:
  - goveralls -coverprofile=profile.cov -service=travis-ci
